
export const INIT_PROBLEMS = "INIT_PROBLEMS"
export const ADD_NEW_PROLEM = "ADD_NEW_PROLEM"
export const UPDATE_ACTIVE_SECTION = "UPDATE_ACTIVE_SECTION"
export const UPDATE_SOLN_STATUS = "UPDATE_SOLN_STATUS"
export const UPDATE_SECTION_STATUS = "UPDATE_SECTION_STATUS"